### ISSUE TITLE
Add Support for Grunt and Similar Tools

### ISSUE THREAD

**Issue by eladius1129** [magento/magento-cloud-docker#105]
How to configure the docker containers to compile less using grunt?

Edit by @YPyltiai:
It appears that Grunt and similar tools do not work because Cloud Docker doesn't support `dependencies` parsing yet (https://devdocs.magento.com/cloud/project/project-conf-files_magento-app.html#dependencies).

**To Do:**
* **Suggested solution:** Add Yarn, Npm, Node, Grunt to PHP Container
* **Alternatively:** Add `dependencies` parsing functionality

**Comment by YPyltiai** [comment]
Hi @eladius1129 ,

Please refer to https://devdocs.magento.com/guides/v2.3/cloud/project/project-conf-files_magento-app.html#hooks section `To compile Sass files using grunt`.  You just need that part where you customize hooks and it should work, since NodeJS is now part of PHP image.

Once you customize hooks, you will need to re-generate your docker configs following the main process outlined here: https://devdocs.magento.com/guides/v2.3/cloud/docker/docker-config.html

Please let us know of the results and if it doesn't work - we can look at it closer.

Thanks,
Yevhenii

**Comment by eladius1129** [comment]
Hi  @YPyltiai, I don't know if you understood me, What I  mean was about this topic https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css_debug.html, can you please give me advice about that.  

What I am talking about is related to your answer?

Thank's  in advanced

**Comment by YPyltiai** [comment]
The process I mentioned above is used for compiling using Grunt. Based on our internal testing it doesn't appear to work with Cloud Docker though, so we'll need to review what's wrong.

@andriyShevtsov may add more details.

**Comment by andriyShevtsov** [comment]
We have internal task for this: MAGECLOUD-4838

**Comment by andriyShevtsov** [comment]
Here is publicly available copy https://github.com/magento/magento-cloud-docker/issues/105

**Comment by shiftedreality** [comment]
Possible add `dependencies` support (https://devdocs.magento.com/cloud/project/project-conf-files_magento-app.html)

**Comment by YPyltiai** [comment]
Internal task: `MAGECLOUD-4921`

**Comment by carlos-reynosa** [comment]
Some of the containers already have npm installed. I run grunt, including building less, commands and i haven't really had a problem with it:

```
#!/bin/bash
docker-compose run -T --rm  deploy npm "$@"

```
```
#!/bin/bash
docker-compose run -T --rm -p 35729:35729 deploy grunt "$@"
```

The only issue is I have to pass the grunt watch ports manually since for some reason it doesn't work when i try to add the port mappings within the override file.
