### ISSUE TITLE
Add possibility to add custom ES plugins

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#151]
As a developer I want my Docker containers to match Cloud environments as closely as possible. 

The Elasticsearch service can contain different plugins that are configured on `services.yaml` file. Cloud docker should read those configurations and install necessary plugins

**Comment by shiftedreality** [comment]
internal issue: https://magento2.atlassian.net/browse/MAGECLOUD-3814

**Comment by G-Arvind** [comment]
HI @shiftedreality  ,
For doing this I tried two approaches,

**_Approach 1 Using docker-entrypoint.sh_**
- Parsed the ES plugins from services.yaml
- Saved these values using the repository
- Got these plugins in Produtcionbuilder, created a new docker-entrypoint.sh file say docker-entrypoint-es.sh
- To include this file inside the container, mounted the volume in docker-compose.yaml, something like this **volume:<path_to_file>/docker-entrypoint-es.sh**
- Included entrypoint in docker-compose.yaml (**entrypoint:docker-entrypoint-es.sh**)

The contents of docker-entrypoint-es.sh will be like this
```
#!/bin/sh
setting up prerequisites
bin/elasticsearch-plugin install analysis-stempel
exec docker-entrypoint.sh elasticsearch
```
**The main problem faced in this approach is, the plugins are not persistent inside the ES container i.e whenever we give docker-compose down the plugins get removed and next time they are getting installed again.**

**_Approach 2 Using Dockerfile_**
- Parsed the ES plugins from services.yaml
- Saved these values using the repository
- Got these plugins in Produtcionbuilder, Included these plugins inside the Dockerfile of ES based on the version (got the ES version from services.yaml)

The Dockerfile will look something like this
```
FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.4
RUN echo "xpack.security.enabled: false" >> /usr/share/elasticsearch/config/elasticsearch.ymlRUN bin/elasticsearch-plugin install analysis-icu && bin/elasticsearch-plugin install analysis-phonetic
EXPOSE 9200 9300
RUN bin/elasticsearch-plugin install analysis-stempel
```
To use this image instead of default ES added a **build:context:  in docker-compose.yaml**

**Here the plugins are persistent.**

Please advise on how to proceed.

Thanks.
cc: @aepod

**Comment by G-Arvind** [comment]
> HI @shiftedreality ,
> For doing this I tried two approaches,
> 
> **_Approach 1 Using docker-entrypoint.sh_**
> 
> * Parsed the ES plugins from services.yaml
> * Saved these values using the repository
> * Got these plugins in Produtcionbuilder, created a new docker-entrypoint.sh file say docker-entrypoint-es.sh
> * To include this file inside the container, mounted the volume in docker-compose.yaml, something like this **volume:<path_to_file>/docker-entrypoint-es.sh**
> * Included entrypoint in docker-compose.yaml (**entrypoint:docker-entrypoint-es.sh**)
> 
> The contents of docker-entrypoint-es.sh will be like this
> 
> ```
> #!/bin/sh
> setting up prerequisites
> bin/elasticsearch-plugin install analysis-stempel
> exec docker-entrypoint.sh elasticsearch
> ```
> 
> **The main problem faced in this approach is, the plugins are not persistent inside the ES container i.e whenever we give docker-compose down the plugins get removed and next time they are getting installed again.**
> 
> **_Approach 2 Using Dockerfile_**
> 
> * Parsed the ES plugins from services.yaml
> * Saved these values using the repository
> * Got these plugins in Produtcionbuilder, Included these plugins inside the Dockerfile of ES based on the version (got the ES version from services.yaml)
> 
> The Dockerfile will look something like this
> 
> ```
> FROM docker.elastic.co/elasticsearch/elasticsearch:6.5.4
> RUN echo "xpack.security.enabled: false" >> /usr/share/elasticsearch/config/elasticsearch.ymlRUN bin/elasticsearch-plugin install analysis-icu && bin/elasticsearch-plugin install analysis-phonetic
> EXPOSE 9200 9300
> RUN bin/elasticsearch-plugin install analysis-stempel
> ```
> 
> To use this image instead of default ES added a **build:context: in docker-compose.yaml**
> 
> **Here the plugins are persistent.**
> 
> Please advise on how to proceed.
> 
> Thanks.

Hi @shiftedreality, any thoughts on this?
Thanks.

**Comment by shiftedreality** [comment]
Hello @G-Arvind ,

Thank you for these approaches. I would suggest trying something like PHP extensions, where they are loaded into env variable and later just enabled in Dockerfile

**Comment by oshmyheliuk** [comment]
Was done in this pr https://github.com/magento/magento-cloud-docker/pull/279 and will be delivered in `1.2.0`
