### ISSUE TITLE
MCLOUD-5929: Upgrade PHPUnit to version 8

### ISSUE THREAD

**Issue by shiftedreality** [magento/magento-cloud-docker#193]
**Is your feature request related to a problem? Please describe.**
[MCLOUD-5929](https://jira.corp.magento.com/browse/MCLOUD-5929):
Since PHPUnit 7 is already deprecated and PHPUnit 8 is stable, we should upgrade our version to 8

https://phpunit.de/supported-versions.html

**Describe the solution you'd like**
PHPUnit is upgraded to version 8

**Comment by drpayyne** [comment]
Hi @shiftedreality, I have a couple doubts regarding the version conflicts present here

-  Would this have any version conflict with the magento-cloud repository since this is used there?
-  There's a migration of tests currently going on from PHPUnit 7 to 8 in the Magento repository. Is it expected for _those_ tests to be migrated to v8 and the magento-cloud-docker tests to be migrated to v9?

CC/ @aepod @mohanelamurugan

**Comment by G-Arvind** [comment]
Hi @shiftedreality, I suppose the PHPUnit 9 does not support PHP 7.2, as we are still using the PHP 7.2 images in magento-cloud-docker is it advisable to proceed with PHPUnit 9 or shall we go with PHPUnit 8.
Thanks.

**Comment by shiftedreality** [comment]
Hello, technically we need PHPUnit only to test the code of Cloud Docker, so there should not be a big deal there.

But I agree to update to PHPUnit 8 first

**Comment by G-Arvind** [comment]
> Hello, technically we need PHPUnit only to test the code of Cloud Docker, so there should not be a big deal there.
> 
> But I agree to update to PHPUnit 8 first

Thanks for the clarifications.
